{% set name = "gdal-driver-nisar" %}
{% set version = "0.1.8" %} # This is the version of NISAR PLUGIN

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # Build from the current directory
  path: .

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - sysroot_linux-64 2.17  # Forces compatibility with older Linux (CentOS 7+)
    - cmake
    - make

  host:
    # Key dependencies to build against
    - gdal {{ gdal }}
    - libgdal-core {{ gdal }}
    - hdf5

  run:
    # Key dependencies to run with
    # same version that was used in the 'host' section.
    - {{ pin_compatible('gdal', exact=True) }}
    - {{ pin_compatible('libgdal-core', exact=True) }}
    # Pin HDF5 to ensure the plugin uses the same HDF5 version it was compiled with
    - {{ pin_compatible('hdf5') }}
test:
  # Add this section to install a full GDAL environment for testing.
  requirements:
    - gdal      # Provides the gdalinfo command-line tool
    - libgdal   # Metapackage that installs all standard driver plugins

  commands:
    # This command will now run in the complete environment.
    - gdalinfo --formats | grep NISAR

about:
  home: # add project's home URL
  license: # add project's license
  summary: 'A GDAL plugin to read NISAR HDF5 files.'
